config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :products do
    resources :comments
  end

  get 'login' => 'users#login'
  post 'login' => 'accessor#user_check'
  get 'register' => 'users#register'
  post 'register' => 'accessor#create_user'

  get 'logout' => 'accessor#logout'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :comments , dependent: :destroy

    validates :name , :presence => true , :length => { minimum: 3 }

end

app/models/user.rb
class User < ApplicationRecord
  validates :username , presence: true , length: { minimum: 4 , maximum: 20 }
  validates :password , presence: true , length: { minimum: 7 , maximum: 24 }

  # User Create
  # if user have exist
  # @return -1
  # if user form check failed
  # @return -2
  # if user fail create
  # @return user
  # if user success create
  # @return user
  def self.create_user reg_f
    @new_user_info = form_build reg_f

    if @new_user_info.nil?
      # -2 is result of User Form check Failed
      return -2
    end

    if !self.exists? @new_user_info
      @user = self.new @new_user_info
      @user.save
      @user
    else
      # -1 is result of User have exist
      -1
    end
  end

  private

  def self.form_build reg_f
    if reg_f[:password].eql? reg_f[:repassword]
      { username: reg_f[:username], password: reg_f[:repassword] }
    else
      nil
    end
  end

end

app/controllers/accessor_controller.rb
class AccessorController < ApplicationController

  skip_before_action :before_require_login, only: [
    :user_check,
    :create_user,
  ]

  # User login check Auth
  # @author SDTTTTT
  def user_check
    @login_form = login_params

    @user = User.find_by @login_form
    if @user.nil?
      flash[:notice] = '你输入的内容很有问题'
      redirect_to '/login'
    else
      store_crrent_user @user
      redirect_to products_path
    end
  end

  def create_user
    @register_form = register_params
    @result = User.create_user @register_form

    if @result.instance_of? User
      unless @result.errors.nil?
        store_crrent_user @result
        redirect_to products_path
      else
        flash[:notice] = 'Sorry! User create Failed'
      end
    else
      case @result
      when -1
        flash[:notice] = 'User have Exist'
      when -2
        flash[:notice] = 'you Password Error'
      end
    end
  end

  def logout
    destroy_crrent_user
    flash[:notice] = 'You have logged out.'
    redirect_to login_path
  end

  private

  def destroy_crrent_user
    session.delete :crrent_user
  end

  def store_crrent_user user
    session[:crrent_user] = {
        uid: user.id,
        username: user.username,
    }
  end

  def login_params
    params.require(:user).permit :username, :password
  end

  def register_params
    params.require(:register_form).permit :username, :password, :repassword
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # TODO 在Coding Studio 环境下这个需要被开启
  # 不然可能因为WebIDE内部的转发而导致无效的Authenticity_token
  skip_before_action :verify_authenticity_token

  before_action :before_require_login
  
  protected
  # Get Crrent User Infomation
  def crrent_user
    User.find session[:crrent_user]['uid']
  end

  private

  def before_require_login
    if session[:crrent_user].nil?
      flash[:notice] = '您必须先登录才能这么做'
      redirect_to login_path
    end
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true
class CommentsController < ApplicationController

  def create
    @comment_info = put_commenter(comment_params)
    @product = Product.find params[:product_id]
    @comment = @product.comments.create @comment_info
    redirect_to product_path @product
  end

  private

  def comment_params
    params.permit :product_id
    params.require(:comment).permit :body
  end

  def put_commenter(params)
    params[:commenter] = crrent_user.username
    params if params.key? :commenter
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    skip_before_action :before_require_login, only: [
        :new,
        :show,
        :index,
    ]

    def new
        @product = Product.new
    end

    def show

        @product_id = params[:id]

        if Product.exists? @product_id
            @product = Product.find @product_id
        else
            @product = Product.find 1
        end
    end

    def index
        @products = Product.all
    end

    def create
        @product = Product.new product_params
        if @product.save
            redirect_to @product
        else
            render 'new'
        end
    end

    def destroy
        @product = Product.find(params[:id])
        @product.destroy
        redirect_to products_path
    end

    def edit
        @product = Product.find(params[:id])
        render "update"
    end

    def update
        @product = Product.find(params[:id])

        if @product.update(product_params)
            redirect_to @product
        else
            render 'edit'
        end
    end

    private

    def product_params
        params.require(:product).permit(:name , :depscription)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :before_require_login , only: [
    :login,
    :register,
  ]

  def login
    @user = User.new
  end

  def register
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/accessor_helper.rb
module AccessorHelper

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Kanon</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <div class="nav-link">
         <% unless session[:crrent_user].nil? %>
      Welcome, ✨<%= session[:crrent_user]['username'] %> ✪ ω ✪
      <%= link_to "Logout", logout_path %>
  <% else %>
      not Login,👋 Click <%= link_to "Login" , login_path %>   OR   ☞ <%= link_to "Register" , register_path %>?
  <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: @product , local: true do |f| %>

  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@product.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :depscription %><br>
    <%= f.text_area :depscription %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/products/index.html.erb
<h1 style="margin: 33px;"> <span class="badge badge-pill badge-dark">Article List</span></h1>

<% if @products.empty? %>

  <div class="product-empty-tip" >
  <h4>
    看起来空空如也，要
    <%= link_to '写' , new_product_path  %> 点什么🐎.
    </h4>
  </div>
<% else %>

  <table class=" table table-light table-borderless" style="width: 88%;margin: auto;">
    <tr>
      <th>Title</th>
      <th>Text</th>
    </tr>

    <% @products.each do |product| %>
      <tr>
        <td>
        <% if product.name.length < 8  %>
        <%= product.name %>
        <% else %>
        <%= product.name[0...8] %>...
        <% end %>
        </td>
        <td>
        <% if product.depscription.length < 8  %>
        <%= product.depscription %>
        <% else %>
        <%= product.depscription[0...8] %>...
        <% end %>
        </td>
        <td><%= link_to 'Show', product_path(product) , { class: 'btn btn-outline-primary' } %></td>
        <td><%= link_to 'Edit',  edit_product_path(product) , { class: 'btn btn-outline-warning'} %></td>
        <td><%= link_to 'Destory', product_path(product), :method => :delete ,:class => 'btn btn-outline-danger' , :data => { :confirm => 'Are you Sure?'  } %></td>
      </tr>


    <% end %>
  </table>

<% end %>

app/views/products/new.html.erb
<h1> this is New </h1>


<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p class="text-justify">
  <p class="lead">

  </p>
</p>

<div class="card opacity-1" style="width: 80%;margin: auto;">
  <div class="card-body">
    <h2 class="card-title"><%= @product.name %></h2>
    <p class="card-text"><%= @product.depscription %></p>
  </div>
</div>

<p>


<br />
<hr style="width: 88%;" />
<br />

<h1 class="display-8" style="margin:0 0 33px 33px;">
<span class="badge badge-secondary">Comments</span>
</h1>

  <% if @product.comments.empty? %>

    <p></p>
    <h5> 评论区空空如也🙃 </h5>

  <% else %>

  <% @product.comments.each do |comment| %>

   <div class="card border-primary mb-3 opacity-1" style="margin-left: 33px;max-width: 18rem;">
  <div class="card-header"><%= comment.commenter %></div>
  <div class="card-body text-primary">
    <p class="card-text"><%= comment.body %></p>
  </div>
  </div>
    <p class="mb-1"></p>

  <% end %>

  <% end %>

</p>

<br />
<hr />
<br />
<p>
<div class='comment-form' >
<h1 class="display-8" style="margin:0 0 33px 33px;">
<span class="badge badge-info">Publish Comment</span>
</h1>
  <%= form_with(model: [@product , @product.comments.build] , local: true) do |f|%>

  <p>
    <%= f.text_area :body , class: 'form-control', style: 'margin:0 0 33px 33px;width: 100%;height: 188px;' %>
  </p>
  <p>
    <%= f.submit 'Commit' , class: 'btn btn-primary', style: 'margin:0 0 33px 33px;width: 50%;' %>
  </p>
  <% end %>
</p>
</div>

app/views/products/update.html.erb
<h1> this is Update </h1>

<%= render 'form' %>

<%= link_to "Back" , products_path  %>

app/views/users/login.html.erb
<p>

  <div class="login-form shadow-sm p-3 mb-5 bg-white rounded" >
  <h1>Login</h1>
  <br />

    <p>
    <% flash.each do |name , msg| %>
     <%= content_tag :div , msg + '🙃' , class: 'alert alert-warning' , role: 'alert'  %>

    <% end %>
  </p>
  <%= form_with model: @user ,url: 'login' , local: true do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username , { class: 'form-control' } %>
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  <br />
    <%= f.label :password %>
    <%= f.text_field :password , { class: 'form-control' } %>
  <br />
    <%= f.submit 'Go' , { class: 'btn btn-primary' } %>
  <% end %>
  </div>
</p>

app/views/users/register.html.erb
<div class="login-form shadow-none p-3 mb-5 bg-light rounded">

<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">Thank you!</h4>
  <p> It's still Beta, but thanks anyway </p>
  <hr>
  <p class="mb-0">By SDTTTTT</p>
</div>

<p>
<h1>Register</h1>

<p>
  <% flash.each do |name , msg| %>
    <%= content_tag :div , msg %>
  <% end %>
</p>

<%= form_with scope: :register_form,url: 'register' , local: true do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username , class: 'form-control' %>
  <br />
  <%= f.label :password  %>
  <%= f.password_field :password , class: 'form-control' %>
  <br />
  <%= f.label 'again password' %>
  <%= f.password_field :repassword , class: 'form-control' %>
  <br />
  <%= f.submit 'OK?' , class: 'btn btn-primary' %>
<% end %>
</p>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron opacity-1" style="width: 88%;margin: 25px auto 0px auto; box-shadow: 2px 2px 10px #888888; ">
  <h1 class="display-4">Welcome to here !</h1>
  <p class="lead"></p>这里是SDTTTT的博客。</p>
  <hr class="my-4">
  <h5><p class="badge badge-pill badge-danger">Status: Beta.</p></h5>
  <h5><p class="badge badge-pill badge-primary">Version: 0.0.2.</p></h5>
  <br />
  <%= link_to 'Go', new_product_path , class:'btn btn-success btn-lg',style: 'width: 24%;' %>
</div>